name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: './'    # path to include
            exclude: './examples/StampFlyController/lib'    # path to exclude
            exclude: './examples/StampFlyController/include'    # path to exclude
            exclude: './examples/StampFlyController/images'    # path to exclude
            exclude: './examples/StampFlyController/guider_fonts'    # path to exclude
          # - check: 'src'
          #   exclude: '(Fonts)' # Exclude file paths containing "Fonts"
          # - check: 'examples'
          #   exclude: ''
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
